# Generated by Django 4.1.1 on 2022-09-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
