# Generated by Django 4.1.1 on 2022-09-25 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileUpload', '0003_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='S3objects',
            new_name='FileObject',
        ),
    ]
